CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD (
    BNO NUMBER(10, 0), 
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE
);

ALTER TABLE TBL_BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (BNO);


INSERT INTO TBL_BOARD (BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목', '테스트 내용', 'user00');

SELECT * FROM TBL_BOARD;

SELECT * FROM TBL_BOARD;

select * from tbl_board where bno > 0;

select BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE  from tbl_board where bno > 0;